name: MSurvivalLobby
version: 2.0
main: pl.msurvival.lobby.MSurvivalLobby
api-version: '1.21'
author: Milekz

commands:
  menu:
    usage: /menu
  menuitem:
    usage: /menuitem
  lobby:
    usage: /lobby
    aliases: [hub]
  survival:
    usage: /survival
  setlobby:
    usage: /setlobby
  setsurvival:
    usage: /setsurvival
  lobbyreload:
    usage: /lobbyreload

permissions:
  msurvivallobby.admin:
    default: op
